=== Churilin/Lab_for_XML_HTML_CSS/Lab_03/XML/Cargo_XML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="Phone">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}-\d{2}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CargoWeightType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CargoVolumeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CostOfTransportationType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,5}\s\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="cargo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TypeOfCargo" type="xs:string"/>
                            <xs:element name="CargoWeight" type="CargoWeightType"/>
                            <xs:element name="CargoVolume" type="CargoVolumeType"/>
                            <xs:element name="WorkPlace" type="xs:string"/>
                            <xs:element name="Address" type="xs:string"/>
                            <xs:element name="Phone" type="Phone"/>
                            <xs:element name="CostOfTransportation" type="CostOfTransportationType"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Churilin/Lab_for_XML_HTML_CSS/Lab_03/XML/Cargo.xml
<?xml version="1.0" encoding="UTF-8"?>
<cargo xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Cargo_XML.xsd">
    <company id = "a">
        <TypeOfCargo>ТНП</TypeOfCargo>
        <CargoWeight>1500</CargoWeight>
        <CargoVolume>3</CargoVolume>
        <WorkPlace>ООО "Мегамаркет"</WorkPlace>
        <Address> СПб, ул. Фучика 15</Address> 
        <Phone> 912-13-15</Phone>
        <СostOfTransportation currency = "RUR">12 500</СostOfTransportation>
    </company>

    <company id = "b">
        <TypeOfCargo>Рулоны</TypeOfCargo>
        <CargoWeight>800</CargoWeight>
        <CargoVolume>5</CargoVolume>
        <WorkPlace>АО "Солюшенс"</WorkPlace>
        <Address> СПб, Парголово, 1-й Верхний переулок 7</Address> 
        <Phone> 823-54-74</Phone>
        <СostOfTransportation currency = "RUR">19 000</СostOfTransportation>
    </company>

    <company id = "c">
        <TypeOfCargo>Стройматериалы</TypeOfCargo>
        <CargoWeight>4000</CargoWeight>
        <CargoVolume>2</CargoVolume>
        <WorkPlace>ООО "Сторойудача"</WorkPlace>
        <Address> СПб, ул. Металлистов 44</Address> 
        <Phone> 567-41-99</Phone>
        <СostOfTransportation currency = "RUR">22 000</СostOfTransportation>
    </company>
</cargo>
