=== Churilin/Lab_for_XML_HTML_CSS/Lab_03/XML/resume_XML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="resume">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candidate" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="LastName" type="xs:string"/>
                            <xs:element name="PatronymicName" type="xs:string"/>
                            <xs:element name="Age" type="xs:integer"/>
                            <xs:element name="WorkPlace" type="xs:string"/>
                            <xs:element name="Post" type="xs:string"/>
                            <xs:element name="DateOfBirth" type="xs:string"/>
                            <xs:element name="Education" type="xs:string"/>
                            <xs:element name="Address" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                            <xs:element name="FamilyStatus" type="xs:string"/>
                            <xs:element name="DesiredSalary">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="currency" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Churilin/Lab_for_XML_HTML_CSS/Lab_03/XML/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resume_XML.xsd"> -->
    <resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resume_XML_part2.xsd">

    <candidate id = "a">
        <Name>Анна</Name>
        <LastName>Ошемкова </LastName>
        <PatronymicName>Петровна</PatronymicName>
        <Age>27</Age>
        <WorkPlace>ООО "Проект"</WorkPlace>
        <Post>менеджер</Post>
        <DateOfBirth> 1980-09-12</DateOfBirth>
        <Education>высшее</Education>
        <Address> СПб, ул. Ленина 3-5</Address> 
        <Phone>123-45-67</Phone>
        <FamilyStatus>замужем</FamilyStatus>
        <DesiredSalary currency = "RUR">30 000</DesiredSalary>
    </candidate>

    <candidate id = "b">
        <Name>Иван</Name>
        <LastName>Сидоренко</LastName>
        <PatronymicName>Иванович </PatronymicName>
        <Age>25</Age>
        <WorkPlace>ООО "РусьСвет" </WorkPlace>
        <Post> экономист</Post>
        <DateOfBirth>1968-03-02</DateOfBirth>
        <Education >высшее</Education>
        <Address> СПб, Серпуховская 13-9</Address>
        <Phone>987-65-54</Phone>
        <FamilyStatus>женат</FamilyStatus>
        <DesiredSalary currency = "RUR">50 000</DesiredSalary>
    </candidate>

    <candidate id = "c">
        <Name>Ольга</Name>
        <LastName> Гашекова</LastName>
        <PatronymicName>Сергеевна</PatronymicName>
        <Age>30</Age>
        <WorkPlace>ООО "Строй"</WorkPlace>
        <Post>менеджер по продажам</Post>
        <DateOfBirth>1976-12-19</DateOfBirth>
        <Education>среднее</Education>
        <Address>СПб, Дбуновская 12-4</Address>
        <Phone>122-33-44</Phone>
        <FamilyStatus >не замужем</FamilyStatus>
        <DesiredSalary currency = "RUR">35 000</DesiredSalary>
    </candidate>
</resume>
